languageCode = "en"
languageName = "English"
weight = 2
title = "Xiaoming Icode's Tech Blog"

[params]
displayName = "English"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "img/blowfish_logo_transparent.png"
description = "A technical blog focused on cloud native and DevOps, sharing practical experience and learning notes"

[params.author]
name = "Xiaoming Icode"
image = "img/blowfish_logo.png"
headline = "**Cloud Native & DevOps Engineer | Golang Enthusiast | Open Source Contributor**"
bio = "Focused on cloud native development and DevOps, sharing practical projects and troubleshooting experience to help more developers."
links = [
  { github = "https://github.com/Ming8087" },
  { email = "czming87@163.com" },
  { bilibili = "https://space.bilibili.com/509191678" }
]